#!/usr/bin/env python3
"""
track-sprint/module-03/src/pipeline_engine.py

Multi-agent pipeline engine coordinating generator, critic, and validator subagents.
Produces deterministic artifacts via headless Spark agent orchestration.
"""
import hashlib
import json
import os
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[3]
MOCK_BIN = REPO_ROOT / "mock-bin"

import sys
sys.path.insert(0, str(Path(__file__).parent))
from rules_engine import SubagentCoordinator, AgentMessage
from artifact_critic import critique_artifact
from patch_generator import apply_patch


class PipelineEngine:
    """Orchestrates multi-agent pipeline: generate → critique → validate."""

    def __init__(self, seed: str = "default-seed"):
        self.seed = seed
        self.coordinator = SubagentCoordinator()
        self._artifacts: dict[str, str] = {}

    def generate_artifact(self, task: str, content_template: str) -> dict:
        """Generate a code artifact via the generator subagent."""
        msg = AgentMessage(
            sender="pipeline", recipient="generator",
            task=task, payload={"template": content_template, "seed": self.seed}
        )
        response = self.coordinator.send(msg)
        # Deterministic artifact content based on seed + task
        artifact_content = f"# Generated by pipeline\n# seed={self.seed}\n# task={task}\n{content_template}\n"
        artifact_hash = hashlib.sha256(artifact_content.encode()).hexdigest()
        self._artifacts[task] = artifact_content
        return {
            "task": task, "content": artifact_content,
            "hash": artifact_hash, "agy_response": response
        }

    def critique_artifact_pipeline(self, task: str) -> dict:
        """Run critic subagent on a generated artifact."""
        content = self._artifacts.get(task, "")
        if not content:
            return {"error": f"No artifact for task: {task}"}
        local_critique = critique_artifact(content, task)
        msg = AgentMessage(
            sender="pipeline", recipient="critic",
            task=f"critique-{task}",
            payload={"content": content[:100]}  # truncate for payload
        )
        response = self.coordinator.send(msg)
        return {"local_critique": local_critique, "agy_response": response}

    def validate_and_patch(self, task: str, patch_text: str, sandbox_root: str) -> dict:
        """Apply patch to sandbox and run validator subagent."""
        patch_result = apply_patch(patch_text, sandbox_root)
        if not patch_result["applied"]:
            return {"validated": False, "patch_result": patch_result}
        msg = AgentMessage(
            sender="pipeline", recipient="validator",
            task=f"validate-{task}",
            payload={"patch_result": patch_result}
        )
        response = self.coordinator.send(msg)
        return {"validated": True, "patch_result": patch_result, "agy_response": response}

    def run_full_pipeline(self, task: str, template: str, sandbox_root: str) -> dict:
        """Run complete generate → critique → validate pipeline."""
        gen = self.generate_artifact(task, template)
        crit = self.critique_artifact_pipeline(task)
        sample_patch = f"--- a/{task}.py\n+++ b/{task}.py\n@@ -1,1 +1,1 @@\n-old\n+new\n"
        val = self.validate_and_patch(task, sample_patch, sandbox_root)
        return {
            "task": task, "generation": gen,
            "critique": crit, "validation": val,
            "status": "COMPLETED",
        }
